### PR TITLE
Prevent double bootstrap run

### PR DESCRIPTION
**Pull request by ricco24**

### CODE REVIEW

**Comment by rootpd** [comment]
Why is this change necessary? How can the bootstrap be called multiple times?

**Comment by ricco24** [comment]
Because **bootstrap()** is called also in **command()** method. 
We are using sentry for error logging and register some processors that depends on services from DI container. So we need work with DI container instance. In bootstrap.php everything works well but in command shell script we can't reach DI container without double bootstrap() call.

**Comment by ricco24** [comment]
Other possible solution is extract all code from command() method to our script, but i don't want to lose track of changes in command() method. Or remove bootstrap() from command() method, but that is BC.

**Comment by ricco24** [comment]
@rootpd what do you think? It is mergable or have i extract all code from command() method?

**Comment by rootpd** [comment]
In the offline discussion we concluded on a bit different change. Based on the Nette sandbox app and the requirement to work with DI container within index.php/command.php, we'll exclude bootstrapping from within [`command()`](https://github.com/remp2020/crm-application-module/blob/master/src/application/Core.php#L53) method and it'll have to be done explicitly by `command.php`.

**Pull request closed without merging**
